# Usar una imagen base ligera de OpenJDK
FROM openjdk:17-jdk-slim AS build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo JAR a la imagen
COPY target/*.jar app.jar

# Exponer el puerto de la aplicación
EXPOSE 8080

# Usar una variable de entorno para mayor flexibilidad
ENV JAVA_OPTS="-Xmx256m"

# Ejecutar la aplicación con optimización de memoria
CMD ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
